apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: dev
  labels:
    app: order-service    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: gcr.io/imre-experiment/order-service:v1.0.0
        livenessProbe:
          httpGet:
            path: /
            port: 8080            
          initialDelaySeconds: 3
          periodSeconds: 3
        readynessProbe:
          httpGet:
            path: /
            port: 8080            
          initialDelaySeconds: 3
          periodSeconds: 3          
        env:        
        - name: NATS_HOST
          valueFrom:
            configMapKeyRef:              
              name: app-config
              key: nats.host
        - name: NATS_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: nats.username
        - name: NATS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: nats.password              
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: dev
  labels:
    app: payment-service    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: gcr.io/imre-experiment/payment-service:v1.0.0
        livenessProbe:
          httpGet:
            path: /
            port: 8081            
          initialDelaySeconds: 3
          periodSeconds: 3
        readynessProbe:
          httpGet:
            path: /
            port: 8081            
          initialDelaySeconds: 3
          periodSeconds: 3          
        env:        
        - name: NATS_HOST
          valueFrom:
            configMapKeyRef:              
              name: app-config
              key: nats.host
        - name: NATS_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: nats.username
        - name: NATS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: nats.password              
        ports:
        - containerPort: 8081

# Baca config



